# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b8d82fa3e6039e43b22a88e1dd36b9e05463850beb6948c0c25644ab66780332b24b86bfecef3e9cab8b30454e7bfe6fcfc55de5bc8568037ed040eb33e7894

test:
  secret_key_base: aba719185b6cba863ff938be2338c33e9d6fbbe6d389425e12fb2f936e4179a15886d54f81343b26bdc1b23f2a19ce1163c8e5eacfa3f147b903b526063fd5db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
