all: equal isint largest sorted


equal: equal.cpp
	g++ -Wall -pedantic -g -o equal equal.cpp

isint: isint.cpp
	g++ -Wall -pedantic -g -o isint isint.cpp

largest: largest.cpp
	g++ -Wall -pedantic -g -o largest largest.cpp

sorted: sorted.cpp
	g++ -Wall -pedantic -g -o sorted sorted.cpp

clean:
	rm -r equal isint largest sorted
